version: '3'

services:
  api:
    build:
      restart: always
      context: .
      args:
        MECHLIB_BRANCH: master
        SATS_BRANCH: feat-integrate-mechlib
    environment:
      SENTRY_DSN: https://53797e613e974dc3a6a0a82b7b936ee2@sentry.io/1538118
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/cavis
      CPLEX_STUDIO_DIR129: /opt/ibm/ILOG/CPLEX_Studio129
    ports:
      - 8080:8080

  mongo:
    restart: always
    image: mongo
    volumes:
      - mongodb:/data/db

  frontend:
    restart: always
    build: ../cavis-frontend
    depends_on:
      - api
    ports:
      - 80:80

volumes:
  mongodb: