version: '3'

services:
  api:
    build: .
    environment:
      CPLEX_STUDIO_DIR129: /opt/ibm/ILOG/CPLEX_Studio129
    ports:
      - 8080:8080

  frontend:
    build:
      context: ../cavis-frontend
      args:
        VUE_APP_API_URL: http://localhost:8080
    depends_on:
      - api
    ports:
      - 80:80