version: '3'

services:
  api:
    build: .
    environment:
      CPLEX_STUDIO_DIR129: /opt/ibm/ILOG/CPLEX_Studio129
    ports:
      - 8080:8080

  frontend:
    build: ../cavis-frontend
    depends_on:
      - api
    ports:
      - 80:80