version: '3'

services:
  api:
    build:
      context: .
      args:
        JOPT_BRANCH: develop
        MECHLIB_BRANCH: master
        SATS_BRANCH: feat-integrate-mechlib
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/cavis
      CPLEX_STUDIO_DIR129: /opt/ibm/ILOG/CPLEX_Studio129
    ports:
      - 8080:8080

  mongo:
    image: mongo
    volumes:
      - mongodb:/data/db

  frontend:
    build: ../cavis-frontend
    depends_on:
      - api
    ports:
      - 80:80

volumes:
  mongodb:
    driver: local
    driver_opts:
      type: none
      device: ${MONGO_DB_PATH:?You must specify the MONGO_DB_PATH variable in your .env file}
      o: bind